---
name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Test:
    name: Lint and build Flipper Application Package
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ’¾ Check out repository
        uses: actions/checkout@v3

      - name: ğŸ¬ Check out Flipper Zero firmware repository
        uses: actions/checkout@v3
        with:
          repository: flipperdevices/flipperzero-firmware
          path: fw

      - name: ğŸ·ï¸ Check out latest stable firmware tag
        working-directory: ./fw
        run: |
          git fetch -t
          git checkout "$(\
            git ls-remote --tags origin \
            | grep -e 'tags/[0-9\.]\+$' \
            | awk '{print $1" "$2}' \
            | sort -V -k 2 \
            | tail -n 1 \
            | awk '{print $2}' \
          )"

      - name: ğŸ©¹ Apply FAP linting patch
        working-directory: ./fw
        run: |
          git apply ../.github/*.patch

      - name: ğŸ”— Symlink application repository within firmware repository
        run: |
          ln -svf ../../.. fw/applications_user/build
          ls -l fw/applications_user
          ls -l fw/applications_user/build
          ls -l fw/applications_user/build/

      - name: ğŸ”¬ Run linters
        working-directory: ./fw
        run: |
          ./fbt lint

      - name: ğŸ“¦ Build Flipper Application Package
        working-directory: ./fw
        run: |
          ./fbt fap_sandbox_app
