---
name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Test:
    name: Lint and build Flipper Application Package
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ¬ Check out Flipper Zero firmware repository
        uses: actions/checkout@v3
        with:
          repository: flipperdevices/flipperzero-firmware

      - name: ğŸ·ï¸ Check out latest stable firmware tag
        run: |
          git checkout "$(\
            git ls-remote --tags origin \
            | grep -e 'tags/[0-9\.]\+$' \
            | awk '{print $1" "$2}' \
            | sort -V -k 2 \
            | tail -n 1 \
            | awk '{print $2}' \
          )"

      - name: ğŸ’¾ Check out repository
        uses: actions/checkout@v3
        with:
          path: applications_user/build

      - name: ğŸ”¥ Build Flipper Application Package
        run: |
          ./fbt fap_sandbox_app
